schedules:
- cron: "0 5 * * *"
  displayName: Daily GC
  branches:
    include:
    - master

trigger: 
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-18.04

variables:
- group: aks-ci
- name: DisableDockerDetector
  value: true

stages:
  - stage: run_basic_lb_e2e
    dependsOn: []
    jobs:
    - job: build_push_ccm_image_job
      timeoutInMinutes: 30
      steps:
        - bash: |
            git show --stat
            echo $REGISTRY_PASSWORD | docker login $REGISTRY_URL -u $REGISTRY_USERNAME --password-stdin
            export IMAGE_REGISTRY=$REGISTRY_URL
            echo "finished"
          displayName: make and push ccm image
          env:
            REGISTRY_URL: $(registry.url)
            REGISTRY_USERNAME: $(registry.username)
            REGISTRY_PASSWORD: $(registry.password)
